version: "2"
linters:
  enable:
    # make sure all errors returned by functions are handled
    - errcheck

    # show how code can be simplified
    - gosimple

    # # make sure code is formatted
    - gofmt

    # examine code and report suspicious constructs, such as Printf calls whose
    # arguments do not align with the format string
    - govet

    # make sure names and comments are used according to the conventions
    - revive

    # detect when assignments to existing variables are not used
    - ineffassign

    # run static analysis and find errors
    - staticcheck

    # find unused variables, functions, structs, types, etc.
    - unused

    # parse and typecheck code
    - typecheck
